services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      # Cette ligne sauvegarde votre connexion de manière permanente dans un dossier 'sessions' local
      - ./sessions:/usr/src/app/.wwebjs_auth
      # Ce dossier contiendra toutes les photos, vidéos, vocaux, etc.
      - ./media:/usr/src/app/media
      # Permet de modifier le frontend en direct test
      - ./public:/usr/src/app/public
    networks:
      - default
      - locapay_dev_default   # Réseau NestJS DEV
      - locapay_default       # Réseau NestJS PROD
    depends_on:
      - db
    shm_size: '512mb'
    ports:
      - "13000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:15-alpine
    container_name: whatsapp-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: whatsapp_logs
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

volumes:
  db-data:

networks:
  locapay_dev_default:
    external: true
  locapay_default:
    external: true
